"""K230 target tracking parameters for the official red-ring target.

This file is intentionally small enough to tune at the match site.  The main
algorithm keeps fallback defaults, then loads this file from /sdcard at boot.

Command sign convention:
  - K230 sends "$K230,valid,yaw,pitch" at 115200 baud on UART2.
  - yaw/pitch are degrees for the MSPM0 gimbal controller.
  - Mode selection is handled by MSPM0; K230 may run continuously.

Tune order:
  1. If the laser aims consistently off-center, adjust the far/near fixed
     laser reference points below.
  2. If it starts too slowly, raise CONTROL_SEND_HZ first.
  3. If it jitters or overshoots, reduce *_CONTROL_MAX_DEG or enlarge deadband.
  4. If far target is lost, relax black-panel thresholds slightly.  Red rings
     only confirm that the black panel is the official target; they are not
     used as the aim center.
"""

# Version tag printed in USB debug output.
SCRIPT_VERSION = "panel_center_v72_mode2_search_gate"
CONTROL_MODE = "panel_center_laser_closed_loop"

# Runtime/debug switches.  Keep USB debug off for standalone competition use.
USB_DEBUG_ENABLED = False
TARGET_CANDIDATE_DEBUG = False
STM32_RX_DEBUG = False
CONTROL_OUTPUT_ENABLED = True
DEFAULT_RUN_SECONDS = None
DIAGNOSE_ONCE = False
FORCE_COMMAND_ENABLED = False
FORCE_YAW = 0.0
FORCE_PITCH = 1.00

# UART/camera startup.  More retries makes unattended boot more tolerant.
LOST_SEND_HZ = 15
CONTROL_SEND_HZ = 45
DEBUG_PRINT_HZ = 8
CAMERA_START_RETRIES = 4
CAMERA_WARMUP_FRAMES = 8
CAMERA_WARMUP_MAX_TRIES = 60
CAMERA_RETRY_DELAY_MS = 120

# Camera is physically mounted rotated clockwise by 90 degrees.
CAMERA_ROTATION_CW_DEG = 90
ERROR_YAW_SIGN = 1.0
ERROR_PITCH_SIGN = 1.0

# White paper ROI.
PAPER_ROI_ENABLED = True
PAPER_THRESHOLD = (40, 100, -50, 50, -65, 65)
PAPER_MIN_PIXELS = 1200
PAPER_MIN_AREA = 1800
PAPER_MIN_W = 70
PAPER_MIN_H = 70
PAPER_MIN_DENSITY = 8
PAPER_MERGE_MARGIN = 6
PAPER_INSET_PX = 2

# Black outer frame / panel fallback.  It is a center fallback, not a corner
# target.  If far range drifts to corners, keep these strict.
SQUARE_THRESHOLD = (0, 20, -128, 127, -128, 127)
SQUARE_RECT_THRESHOLD = 8000
SQUARE_EDGE_MARGIN = 0
SQUARE_MIN_W = 55
SQUARE_MIN_H = 55
SQUARE_MIN_PIXELS = 80
SQUARE_MERGE_MARGIN = 8
SQUARE_MIN_ASPECT = 0.25
SQUARE_MAX_ASPECT = 4.00
SQUARE_MIN_DENSITY = 1
SQUARE_MAX_DENSITY = 85
SQUARE_UNION_MIN_BLOBS = 2
SQUARE_UNION_MIN_PIXELS = 180
SQUARE_PART_MIN_PIXELS = 18
SQUARE_PART_MIN_AREA = 25
SQUARE_RECT_MIN_SCORE = 2500
SQUARE_PAPER_RELAX_PX = 18
SQUARE_CLIPPED_FALLBACK_ENABLED = True
SQUARE_CLIPPED_MIN_PARTS = 1
SQUARE_CLIPPED_MIN_PIXELS = 140
SQUARE_CLIPPED_MIN_W = 45
SQUARE_CLIPPED_MIN_H = 45
SQUARE_CLIPPED_PAPER_RELAX_PX = 28
FRAME_CENTER_MIN_W = 70
FRAME_CENTER_MIN_H = 80
FRAME_CENTER_MIN_SCORE = 20000
FRAME_CENTER_MIN_ASPECT = 0.45
FRAME_CENTER_MAX_ASPECT = 1.80
FRAME_CENTER_MIN_EDGE_PX = 45
FRAME_PART_MAX_ASPECT = 2.20
FRAME_PART_MIN_EDGE_PX = 8
FRAME_CENTER_FALLBACK_ENABLED = True
PAPER_CENTER_FALLBACK_ENABLED = True
RECT_TARGET_ENABLED = False
BLACK_FRAME_FALLBACK_ENABLED = False
FRAME_PART_RECENTER_ENABLED = True
FRAME_PART_RECENTER_GAIN = 0.55
FRAME_PART_RECENTER_DEADBAND_PX = 18.0
FRAME_PART_RECENTER_MAJOR_AXIS_RATIO = 1.35

# Official target: red concentric rings on a black-framed panel.  Red is only
# a confirmation/anchor signal; closed-loop aiming uses the black panel center.
RED_RINGS_TARGET_ENABLED = True
RED_RINGS_THRESHOLDS = (
    (0, 100, 8, 127, -80, 45),
    (0, 100, 18, 127, -80, 60),
)
RED_RINGS_MIN_PART_PIXELS = 5
RED_RINGS_MIN_PART_AREA = 5
RED_RINGS_MIN_PART_DENSITY = 1.0
RED_RINGS_MAX_PART_DENSITY = 100.0
RED_RINGS_SOLID_PART_MIN_AREA = 320
RED_RINGS_SOLID_PART_MAX_DENSITY = 72.0
RED_RINGS_MIN_TOTAL_PIXELS = 10
RED_RINGS_MIN_PARTS = 1
RED_RINGS_MIN_W = 8
RED_RINGS_MIN_H = 1
RED_RINGS_MIN_ASPECT = 0.12
RED_RINGS_MAX_ASPECT = 8.00
RED_RINGS_UNION_MIN_DENSITY = 2.0
RED_RINGS_UNION_MAX_DENSITY = 100.0
RED_RINGS_COMPLETE_MIN_W = 60
RED_RINGS_COMPLETE_MIN_H = 80
RED_RINGS_COMPLETE_MIN_ASPECT = 0.55
RED_RINGS_COMPLETE_MAX_ASPECT = 1.85
RED_RINGS_COMPLETE_EDGE_MARGIN_PX = 1
RED_RINGS_COMPLETE_AIM_ENABLED = True
RED_RINGS_DIRECT_AIM_FALLBACK_ENABLED = True
RED_RINGS_DIRECT_AIM_MIN_SCORE = 8000
RED_RINGS_DIRECT_AIM_MIN_EDGE_PX = 5
RED_RINGS_PART_RECENTER_ENABLED = False
RED_RINGS_PART_RECENTER_GAIN = 0.50
RED_RINGS_PART_EDGE_GAIN = 0.75
RED_RINGS_PART_CONTROL_MAX_DEG = 0.06
RED_RINGS_PART_DEADBAND_PX = 12.0
RED_RINGS_PART_FINE_RADIUS_PX = 35.0
RED_RINGS_PART_FINE_CONTROL_MAX_DEG = 0.04
RED_RINGS_PAPER_RELAX_PX = 8
RED_RINGS_MAX_CENTER_JUMP_PX = 80
RED_RINGS_REJECT_HOLD_MISSES = 45
RED_RINGS_PART_EDGE_COMMAND_ENABLED = True
RED_RINGS_PART_EDGE_COMMAND_MARGIN_PX = 12
RED_RINGS_PART_EDGE_ERR_PX = 8.0
RED_RINGS_PART_TRACK_MIN_W = 70
RED_RINGS_PART_TRACK_MIN_H = 70
RED_RINGS_PART_TRACK_MIN_SCORE = 4500
RED_RINGS_PART_FIXED_REF_MIN_H = 70
RED_RINGS_PART_FIXED_REF_MIN_SCORE = 2500
RED_RINGS_PART_CONTROL_ENABLED = True
RED_RINGS_DEBUG = False

# Far target black-panel center fallback.
RED_PANEL_FRAME_ENABLED = True
RED_PANEL_FRAME_MIN_PIXELS = 55
RED_PANEL_FRAME_MIN_AREA = 1000
RED_PANEL_FRAME_MIN_W = 34
RED_PANEL_FRAME_MIN_H = 44
RED_PANEL_FRAME_MIN_ASPECT = 0.22
RED_PANEL_FRAME_MAX_ASPECT = 1.20
RED_PANEL_FRAME_MIN_DENSITY = 1.5
RED_PANEL_FRAME_MAX_DENSITY = 88.0
RED_PANEL_FRAME_MERGE_MARGIN = 4
RED_PANEL_FRAME_PAPER_RELAX_PX = 26
RED_PANEL_FRAME_ROI_INSET_PX = 2
RED_PANEL_FRAME_COMPLETE_EDGE_PX = 2
RED_PANEL_ANCHOR_ENABLED = True
RED_PANEL_ANCHOR_PAD_X = 85
RED_PANEL_ANCHOR_PAD_Y = 75
RED_PANEL_ANCHOR_THRESHOLD = (0, 45, -128, 127, -128, 127)
RED_PANEL_ANCHOR_DARK_R = 75
RED_PANEL_ANCHOR_DARK_G = 75
RED_PANEL_ANCHOR_DARK_B = 75
RED_PANEL_ANCHOR_MIN_DARK_RATIO = 0.18
RED_PANEL_ANCHOR_MIN_W = 34
RED_PANEL_ANCHOR_MIN_H = 44
RED_PANEL_ANCHOR_MAX_ASPECT = 1.80
RED_PANEL_ANCHOR_MAX_RED_CENTER_RATIO = 0.70
RED_PANEL_EDGE_ESTIMATE_ENABLED = True
RED_PANEL_EDGE_PAD_X = 95
RED_PANEL_EDGE_PAD_Y = 95
RED_PANEL_EDGE_OVERLAP_RATIO = 0.12
RED_PANEL_EDGE_MIN_PIXELS = 12
RED_PANEL_EDGE_MIN_AREA = 12
RED_PANEL_EDGE_MIN_DENSITY = 1.0
RED_PANEL_EDGE_MAX_DENSITY = 98.0
RED_PANEL_EDGE_MIN_SPAN_RATIO = 0.28
RED_PANEL_EDGE_MIN_PAIR_W = 42
RED_PANEL_EDGE_MIN_PAIR_H = 52
RED_PANEL_EDGE_HEIGHT_FROM_WIDTH = 1.45
RED_PANEL_EDGE_MAX_RED_CENTER_RATIO = 0.68
RED_PANEL_EDGE_DEBUG = False
RED_PANEL_RECT_CENTER_PRIORITY_ENABLED = True
RED_PANEL_CENTER_FALLBACK_ENABLED = True
RED_PANEL_CENTER_MIN_RED_PIXELS = 20
RED_PANEL_CENTER_MIN_RED_PARTS = 3
RED_PANEL_CENTER_DEADBAND_PX = 8.0
RED_PANEL_CENTER_X_DEADBAND_PX = 14.0
RED_PANEL_CENTER_FINE_RADIUS_PX = 52.0
RED_PANEL_CENTER_CONTROL_MAX_DEG = 0.06
RED_PANEL_CENTER_FINE_CONTROL_MAX_DEG = 0.04
RED_PANEL_CENTER_TARGET_WARMUP = 1
RED_PANEL_CENTER_STABLE_SPREAD_PX = 10.0
RED_PANEL_CENTER_MAX_JUMP_PX = 24
RED_PANEL_MODE2_FRAME_FALLBACK_ENABLED = True
RED_PANEL_MODE2_FRAME_MIN_W = 42
RED_PANEL_MODE2_FRAME_MIN_H = 52
RED_PANEL_MODE2_FRAME_MIN_SCORE = 2400

# Laser is treated as a fixed camera-relative reference.  Recalibrate these
# if the camera/laser mount changes.  For the official panel, frame image
# width is used as a rough range estimate: far/small target -> far point,
# near/large target -> near point.
FIXED_LASER_ENABLED = True
REAL_LASER_PREFERRED = False
REAL_LASER_MIN_SCORE = 650
LASER_ON_TARGET_RELAX_PX = 6
OFF_PANEL_RECOVERY_ENABLED = True
OFF_PANEL_RECOVERY_CONTROL_MAX_DEG = 0.04
OFF_PANEL_RECOVERY_DEADBAND_PX = 8.0
OFF_PANEL_RECOVERY_MAJOR_AXIS_RATIO = 1.30
OFF_PANEL_RECOVERY_TARGET_HOLD_ENABLED = False
OFF_PANEL_RECOVERY_MAX_TARGET_JUMP_PX = 120
FIXED_LASER_CLOSED_LOOP_ENABLED = True
FIXED_LASER_CONTROL_MAX_DEG = 0.04
FIXED_LASER_DEADBAND_PX = 5.0
FIXED_LASER_CX = 207.0
FIXED_LASER_CY = 82.0
FIXED_LASER_RANGE_REF_ENABLED = True
# Camera is mounted 90 degrees clockwise. The target's horizontal width in
# the screenshot corresponds to the real-world target height, so use image W
# as the range proxy for fixed laser reference interpolation.
FIXED_LASER_RANGE_BY_FRAME_IMAGE_W = True
FIXED_LASER_FAR_TARGET_W = 70.0
FIXED_LASER_NEAR_TARGET_W = 125.0
FIXED_LASER_FAR_TARGET_H = 150.0
FIXED_LASER_FAR_CX = 207.0
FIXED_LASER_FAR_CY = 82.0
FIXED_LASER_NEAR_TARGET_H = 220.0
FIXED_LASER_NEAR_CX = 207.0
FIXED_LASER_NEAR_CY = 82.0
FIXED_LASER_RED_RING_PANEL_H_SCALE = 1.65
LASER_LOST_RECOVERY_ENABLED = False
LASER_LOST_RECOVERY_DEG = 0.08
LASER_THRESHOLD = (45, 100, 22, 127, -30, 127)
LASER_MIN_PIXELS = 3
LASER_MIN_AREA = 3
LASER_MIN_W = 2
LASER_MIN_H = 2
LASER_MAX_AREA = 90
LASER_MAX_W = 10
LASER_MAX_H = 10
LASER_MIN_DENSITY = 35.0
LASER_MIN_ROUNDNESS = 0.45
LASER_MIN_BRIGHT_PIXELS = 2
LASER_BRIGHT_THRESHOLD = (52, 100, 18, 127, -10, 127)
LASER_HINT_MAX_DIST_PX = 70
LASER_REACQUIRE_MAX_DIST_PX = 220
LASER_PAPER_RELAX_PX = 80

# Filters and control.  Smaller per-frame degree plus higher send rate gives
# smoother motion.  Raise CONTROL_SEND_HZ before raising max degrees.
TARGET_FILTER_WINDOW = 2
TARGET_FILTER_ALPHA = 0.98
TARGET_FILTER_DEADBAND_PX = 0.3
TARGET_WARMUP = 1
LASER_FILTER_WINDOW = 2
LASER_FILTER_ALPHA = 0.85
LASER_FILTER_DEADBAND_PX = 0.4
LASER_WARMUP = 2
ERROR_DEADBAND_PX = 2.0
CONTROL_GAIN = 0.45
CONTROL_MAX_DEG = 0.16
FRAME_CENTER_DEADBAND_PX = 9.0
FRAME_CENTER_FINE_RADIUS_PX = 38.0
FRAME_CENTER_FINE_CONTROL_MAX_DEG = 0.04
RED_RINGS_DEADBAND_PX = 14.0
RED_RINGS_FINE_RADIUS_PX = 36.0
RED_RINGS_FINE_CONTROL_MAX_DEG = 0.04
RED_RINGS_SAFE_CONTROL_MAX_DEG = 0.04
PAPER_CENTER_CONTROL_MAX_DEG = 0.08
FRAME_PART_CONTROL_MAX_DEG = 0.08
MAX_TARGET_JUMP_PX = 70
MAX_LASER_JUMP_PX = 45
TARGET_HOLD_MISSES = 5
LASER_HOLD_MISSES = 8
TARGET_STABLE_SPREAD_PX = 30
LASER_STABLE_SPREAD_PX = 45
TARGET_HOLD_MS = 900
FRAME_CENTER_LOCK_FRAMES = 8
FRAME_CENTER_LOCK_MARGIN_PX = 26

# Soft pitch guard for far/tilted views.  It prevents runaway upward commands
# when the target appears too high in the image.
PITCH_GUARD_ENABLED = True
PITCH_GUARD_MIN_TARGET_CY = 62.0
PITCH_GUARD_SOFT_TARGET_CY = 85.0
PITCH_GUARD_UP_CMD_SIGN = -1.0
PITCH_GUARD_MAX_UP_CMD = 0.04
