#ifndef BOARD_PINS_H_
#define BOARD_PINS_H_

#include "ti_msp_dl_config.h"
#include <stdint.h>

#define BOARD_PWM_PERIOD_COUNTS (1600U)

/* Motor PWM: configured by SysConfig in timx_timer_mode_pwm_edge_sleep.syscfg. */
#define BOARD_PWM_INST PWM_0_INST
#define BOARD_PWM_LEFT_CC_INDEX GPIO_PWM_0_C0_IDX
#define BOARD_PWM_RIGHT_CC_INDEX GPIO_PWM_0_C1_IDX

#define BOARD_L_IN1_PORT GPIOA
#define BOARD_L_IN1_PIN DL_GPIO_PIN_8
#define BOARD_L_IN1_IOMUX IOMUX_PINCM19
#define BOARD_L_IN2_PORT GPIOA
#define BOARD_L_IN2_PIN DL_GPIO_PIN_27
#define BOARD_L_IN2_IOMUX IOMUX_PINCM60

#define BOARD_R_IN1_PORT GPIOB
#define BOARD_R_IN1_PIN DL_GPIO_PIN_0
#define BOARD_R_IN1_IOMUX IOMUX_PINCM12
#define BOARD_R_IN2_PORT GPIOB
#define BOARD_R_IN2_PIN DL_GPIO_PIN_6
#define BOARD_R_IN2_IOMUX IOMUX_PINCM23

#define BOARD_MOTOR_STBY_PORT GPIOB
#define BOARD_MOTOR_STBY_PIN DL_GPIO_PIN_18
#define BOARD_MOTOR_STBY_IOMUX IOMUX_PINCM44

#define BOARD_MOTOR_LEFT_INVERT (0)
#define BOARD_MOTOR_RIGHT_INVERT (0)
#define BOARD_MOTOR_MAX_PERCENT (28)
#define BOARD_MOTOR_START_PERCENT (12)

/* 8-channel grayscale sensor with AD0/AD1/AD2 mux and one OUT pin. */
#define BOARD_GRAY_AD0_PORT GPIOB
#define BOARD_GRAY_AD0_PIN DL_GPIO_PIN_7
#define BOARD_GRAY_AD0_IOMUX IOMUX_PINCM24
#define BOARD_GRAY_AD1_PORT GPIOB
#define BOARD_GRAY_AD1_PIN DL_GPIO_PIN_8
#define BOARD_GRAY_AD1_IOMUX IOMUX_PINCM25
#define BOARD_GRAY_AD2_PORT GPIOA
#define BOARD_GRAY_AD2_PIN DL_GPIO_PIN_22
#define BOARD_GRAY_AD2_IOMUX IOMUX_PINCM47
#define BOARD_GRAY_OUT_PORT GPIOB
#define BOARD_GRAY_OUT_PIN DL_GPIO_PIN_4
#define BOARD_GRAY_OUT_IOMUX IOMUX_PINCM17
#define BOARD_GRAY_BLACK_IS_HIGH (1U)
#define BOARD_GRAY_SETTLE_US (80U)

/* Rear encoders are used for distance/keypoint estimation. */
#define BOARD_LR_ENC_A_PORT GPIOB
#define BOARD_LR_ENC_A_PIN DL_GPIO_PIN_19
#define BOARD_LR_ENC_A_IOMUX IOMUX_PINCM45
#define BOARD_LR_ENC_B_PORT GPIOB
#define BOARD_LR_ENC_B_PIN DL_GPIO_PIN_24
#define BOARD_LR_ENC_B_IOMUX IOMUX_PINCM52

#define BOARD_RR_ENC_A_PORT GPIOA
#define BOARD_RR_ENC_A_PIN DL_GPIO_PIN_26
#define BOARD_RR_ENC_A_IOMUX IOMUX_PINCM59
#define BOARD_RR_ENC_B_PORT GPIOA
#define BOARD_RR_ENC_B_PIN DL_GPIO_PIN_25
#define BOARD_RR_ENC_B_IOMUX IOMUX_PINCM55

#define BOARD_LR_ENCODER_INVERT (0)
#define BOARD_RR_ENCODER_INVERT (1)
#define BOARD_ENCODER_COUNTS_PER_REV (530)
#define BOARD_WHEEL_DIAMETER_MM (65)

/* IMU UART0: ATK-MS901M/JY901-style 0x55 0x53 frame, 115200 8N1. */
#define BOARD_IMU_UART UART0
#define BOARD_IMU_UART_IRQN UART0_INT_IRQn
#define BOARD_IMU_TX_IOMUX IOMUX_PINCM21
#define BOARD_IMU_TX_IOMUX_FUNC IOMUX_PINCM21_PF_UART0_TX
#define BOARD_IMU_RX_IOMUX IOMUX_PINCM22
#define BOARD_IMU_RX_IOMUX_FUNC IOMUX_PINCM22_PF_UART0_RX
#define BOARD_IMU_BAUD (115200U)
#define BOARD_IMU_FRESH_MS (300U)

/* Sound/light interaction. */
#define BOARD_KEY_PORT GPIOB
#define BOARD_KEY_PIN DL_GPIO_PIN_2
#define BOARD_KEY_IOMUX IOMUX_PINCM15
#define BOARD_KEY_LONG_PRESS_MS (800U)
#define BOARD_TASK_SLOT_MS (700U)
#define BOARD_TASK_COUNT (6U)
#define BOARD_TASK_MAX_SLOT (9U)

#define BOARD_BEEP_PORT GPIOB
#define BOARD_BEEP_PIN DL_GPIO_PIN_13
#define BOARD_BEEP_IOMUX IOMUX_PINCM30

#define BOARD_LED_R_PORT GPIOB
#define BOARD_LED_R_PIN DL_GPIO_PIN_17
#define BOARD_LED_R_IOMUX IOMUX_PINCM43
#define BOARD_LED_G_PORT GPIOA
#define BOARD_LED_G_PIN DL_GPIO_PIN_15
#define BOARD_LED_G_IOMUX IOMUX_PINCM37

/* SSD1306 OLED, software I2C. OLED SCK/SCL -> PA31, SDA -> PA28. */
#define BOARD_OLED_SDA_PORT GPIOA
#define BOARD_OLED_SDA_PIN DL_GPIO_PIN_28
#define BOARD_OLED_SDA_IOMUX IOMUX_PINCM3
#define BOARD_OLED_SCL_PORT GPIOA
#define BOARD_OLED_SCL_PIN DL_GPIO_PIN_31
#define BOARD_OLED_SCL_IOMUX IOMUX_PINCM6
#define BOARD_OLED_I2C_ADDR (0x3CU)

/* Reserved for later laser control. Not used by the line-following code. */
#define BOARD_LASER_SW_PORT GPIOB
#define BOARD_LASER_SW_PIN DL_GPIO_PIN_15
#define BOARD_LASER_SW_IOMUX IOMUX_PINCM32

#define BOARD_SERVO_PAN_CHANNEL (0U)
#define BOARD_SERVO_TILT_CHANNEL (1U)
#define BOARD_SERVO_CENTER_DEG (90U)
#define BOARD_SERVO_MIN_DEG (30U)
#define BOARD_SERVO_MAX_DEG (150U)
#define BOARD_AIM_TARGET_QUALITY_MIN (30U)
#define BOARD_AIM_LOCK_ERROR (12)
#define BOARD_AIM_LOCK_MS (350U)
#define BOARD_AIM_LASER_PULSE_MS (300U)
#define BOARD_AIM_SERVO_STEP_DIV (25)
#define BOARD_DRAW_STEP_MS (600U)

/* K230 vision UART1 reserve: M0 PA17 TX -> K230 RX, M0 PA18 RX <- K230 TX. */
#define BOARD_K230_UART UART1
#define BOARD_K230_TX_IOMUX IOMUX_PINCM39
#define BOARD_K230_TX_IOMUX_FUNC IOMUX_PINCM39_PF_UART1_TX
#define BOARD_K230_RX_IOMUX IOMUX_PINCM40
#define BOARD_K230_RX_IOMUX_FUNC IOMUX_PINCM40_PF_UART1_RX
#define BOARD_K230_BAUD (115200U)
#define BOARD_K230_FRESH_MS (300U)

/* Line-following and fallback tuning. */
#define BOARD_LOOP_PERIOD_MS (10U)
#define BOARD_LINE_KP (5)
#define BOARD_LINE_KD (12)
#define BOARD_HEADING_KP (10)
#define BOARD_LOST_HEADING_HOLD_MS (2500U)
#define BOARD_LOST_STOP_MS (5000U)
#define BOARD_IMU_TAKEOVER_BEEP_MS (60U)
#define BOARD_IMU_FEEDBACK_WARN_X10 (80)
#define BOARD_IMU_FEEDBACK_RED_BLINK_MS (200U)
#define BOARD_IMU_FEEDBACK_BEEP_MS (40U)
#define BOARD_IMU_FEEDBACK_BEEP_INTERVAL_MS (600U)
#define BOARD_SEARCH_ENTER_BEEP_MS (180U)
#define BOARD_SEARCH_RED_BLINK_MS (100U)
#define BOARD_SEARCH_BEEP_MS (80U)
#define BOARD_SEARCH_BEEP_INTERVAL_MS (500U)
#define BOARD_SELFTEST_MOTOR_PERCENT (10)
#define BOARD_SELFTEST_MOTOR_ON_MS (700U)
#define BOARD_SELFTEST_MOTOR_PERIOD_MS (1500U)
#define BOARD_SELFTEST_ENCODER_DELTA_COUNTS (4)
#define BOARD_SELFTEST_IMU_DELTA_X10 (150)
#define BOARD_STRAIGHT_TEST_DISTANCE_MM (500)
#define BOARD_STRAIGHT_TEST_BASE_PERCENT (12)
#define BOARD_STRAIGHT_ENCODER_KP (3)
#define BOARD_STRAIGHT_YAW_KP (8)
#define BOARD_LAP_DISTANCE_MM (3200)
#define BOARD_AUTO_TRACE_TIMEOUT_MS (30000U)
#define BOARD_TRACE_AIM_TIMEOUT_MS (40000U)
#define BOARD_AIM_TIMEOUT_MS (5000U)
#define BOARD_DYNAMIC_AIM_TIMEOUT_MS (30000U)
#define BOARD_SYNC_DRAW_TIMEOUT_MS (8000U)
#define BOARD_FOUR_LAPS_TIMEOUT_MS (120000U)
#define BOARD_OLED_REFRESH_MS (200U)

/*
 * Calibrate these on the real track. Values are cumulative distance from A:
 * B, C, D, back to A. Set an entry to 0 to disable that keypoint.
 */
static const int32_t BOARD_KEYPOINT_DISTANCE_MM[4] = {800, 1600, 2400, 3200};
#define BOARD_KEYPOINT_TOLERANCE_MM (60)
#define BOARD_KEYPOINT_PAUSE_MS (300U)

#endif
