"""K230 target tracking parameters for the official red-ring target.

This file is intentionally small enough to tune at the match site.  The main
algorithm keeps fallback defaults, then loads this file from /sdcard at boot.

Command sign convention:
  - K230 sends "$K230,valid,yaw,pitch" at 115200 baud on UART2.
  - yaw/pitch are degrees for the MSPM0 gimbal controller.
  - Mode selection is handled by MSPM0; K230 may run continuously.

Tune order:
  1. If the laser aims consistently off-center, adjust FIXED_LASER_CX/CY.
  2. If it starts too slowly, raise CONTROL_SEND_HZ first.
  3. If it jitters or overshoots, reduce *_CONTROL_MAX_DEG or enlarge deadband.
  4. If far target is lost, relax red-ring/frame thresholds slightly.
"""

# Version tag printed in USB debug output.
SCRIPT_VERSION = "red_rings_v56_autorun_config"
CONTROL_MODE = "red_rings_laser_closed_loop"

# Runtime/debug switches.  Keep USB debug off for standalone competition use.
USB_DEBUG_ENABLED = False
TARGET_CANDIDATE_DEBUG = False
STM32_RX_DEBUG = False
CONTROL_OUTPUT_ENABLED = True
DEFAULT_RUN_SECONDS = None
DIAGNOSE_ONCE = False
FORCE_COMMAND_ENABLED = False
FORCE_YAW = 0.0
FORCE_PITCH = 1.00

# UART/camera startup.  More retries makes unattended boot more tolerant.
LOST_SEND_HZ = 15
CONTROL_SEND_HZ = 45
DEBUG_PRINT_HZ = 8
CAMERA_START_RETRIES = 4
CAMERA_WARMUP_FRAMES = 8
CAMERA_WARMUP_MAX_TRIES = 60
CAMERA_RETRY_DELAY_MS = 120

# Camera is physically mounted rotated clockwise by 90 degrees.
CAMERA_ROTATION_CW_DEG = 90
ERROR_YAW_SIGN = 1.0
ERROR_PITCH_SIGN = 1.0

# White paper ROI.
PAPER_ROI_ENABLED = True
PAPER_THRESHOLD = (40, 100, -50, 50, -65, 65)
PAPER_MIN_PIXELS = 1200
PAPER_MIN_AREA = 1800
PAPER_MIN_W = 70
PAPER_MIN_H = 70
PAPER_MIN_DENSITY = 8
PAPER_MERGE_MARGIN = 6
PAPER_INSET_PX = 2

# Black outer frame / panel fallback.  It is a center fallback, not a corner
# target.  If far range drifts to corners, keep these strict.
SQUARE_THRESHOLD = (0, 20, -128, 127, -128, 127)
SQUARE_RECT_THRESHOLD = 8000
SQUARE_EDGE_MARGIN = 0
SQUARE_MIN_W = 55
SQUARE_MIN_H = 55
SQUARE_MIN_PIXELS = 80
SQUARE_MERGE_MARGIN = 8
SQUARE_MIN_ASPECT = 0.25
SQUARE_MAX_ASPECT = 4.00
SQUARE_MIN_DENSITY = 1
SQUARE_MAX_DENSITY = 85
SQUARE_UNION_MIN_BLOBS = 2
SQUARE_UNION_MIN_PIXELS = 180
SQUARE_PART_MIN_PIXELS = 18
SQUARE_PART_MIN_AREA = 25
SQUARE_RECT_MIN_SCORE = 2500
SQUARE_PAPER_RELAX_PX = 18
SQUARE_CLIPPED_FALLBACK_ENABLED = True
SQUARE_CLIPPED_MIN_PARTS = 1
SQUARE_CLIPPED_MIN_PIXELS = 140
SQUARE_CLIPPED_MIN_W = 45
SQUARE_CLIPPED_MIN_H = 45
SQUARE_CLIPPED_PAPER_RELAX_PX = 28
FRAME_CENTER_MIN_W = 70
FRAME_CENTER_MIN_H = 80
FRAME_CENTER_MIN_SCORE = 20000
FRAME_CENTER_MIN_ASPECT = 0.45
FRAME_CENTER_MAX_ASPECT = 1.80
FRAME_CENTER_MIN_EDGE_PX = 45
FRAME_PART_MAX_ASPECT = 2.20
FRAME_PART_MIN_EDGE_PX = 8
FRAME_CENTER_FALLBACK_ENABLED = True
PAPER_CENTER_FALLBACK_ENABLED = True
RECT_TARGET_ENABLED = False
BLACK_FRAME_FALLBACK_ENABLED = False
FRAME_PART_RECENTER_ENABLED = True
FRAME_PART_RECENTER_GAIN = 0.55
FRAME_PART_RECENTER_DEADBAND_PX = 18.0
FRAME_PART_RECENTER_MAJOR_AXIS_RATIO = 1.35

# Official target: red concentric rings.  Complete rings are precise target;
# thin/partial rings are only a recovery cue.
RED_RINGS_TARGET_ENABLED = True
RED_RINGS_THRESHOLDS = (
    (0, 100, 8, 127, -80, 45),
    (0, 100, 18, 127, -80, 60),
)
RED_RINGS_MIN_PART_PIXELS = 5
RED_RINGS_MIN_PART_AREA = 5
RED_RINGS_MIN_PART_DENSITY = 1.0
RED_RINGS_MAX_PART_DENSITY = 100.0
RED_RINGS_SOLID_PART_MIN_AREA = 320
RED_RINGS_SOLID_PART_MAX_DENSITY = 72.0
RED_RINGS_MIN_TOTAL_PIXELS = 10
RED_RINGS_MIN_PARTS = 1
RED_RINGS_MIN_W = 8
RED_RINGS_MIN_H = 1
RED_RINGS_MIN_ASPECT = 0.12
RED_RINGS_MAX_ASPECT = 8.00
RED_RINGS_UNION_MIN_DENSITY = 2.0
RED_RINGS_UNION_MAX_DENSITY = 100.0
RED_RINGS_COMPLETE_MIN_W = 85
RED_RINGS_COMPLETE_MIN_H = 85
RED_RINGS_COMPLETE_MIN_ASPECT = 0.55
RED_RINGS_COMPLETE_MAX_ASPECT = 1.85
RED_RINGS_COMPLETE_EDGE_MARGIN_PX = 1
RED_RINGS_PART_RECENTER_ENABLED = False
RED_RINGS_PART_RECENTER_GAIN = 0.50
RED_RINGS_PART_EDGE_GAIN = 0.75
RED_RINGS_PART_CONTROL_MAX_DEG = 0.08
RED_RINGS_PART_DEADBAND_PX = 12.0
RED_RINGS_PART_FINE_RADIUS_PX = 35.0
RED_RINGS_PART_FINE_CONTROL_MAX_DEG = 0.06
RED_RINGS_PAPER_RELAX_PX = -10
RED_RINGS_MAX_CENTER_JUMP_PX = 26
RED_RINGS_REJECT_HOLD_MISSES = 45
RED_RINGS_PART_EDGE_COMMAND_ENABLED = True
RED_RINGS_PART_EDGE_COMMAND_MARGIN_PX = 20
RED_RINGS_PART_CONTROL_ENABLED = True
RED_RINGS_DEBUG = False

# Far target black-panel center fallback.
RED_PANEL_FRAME_ENABLED = True
RED_PANEL_FRAME_MIN_PIXELS = 55
RED_PANEL_FRAME_MIN_AREA = 1000
RED_PANEL_FRAME_MIN_W = 34
RED_PANEL_FRAME_MIN_H = 44
RED_PANEL_FRAME_MIN_ASPECT = 0.22
RED_PANEL_FRAME_MAX_ASPECT = 1.20
RED_PANEL_FRAME_MIN_DENSITY = 1.5
RED_PANEL_FRAME_MAX_DENSITY = 88.0
RED_PANEL_FRAME_MERGE_MARGIN = 4
RED_PANEL_FRAME_PAPER_RELAX_PX = 26
RED_PANEL_FRAME_ROI_INSET_PX = 2
RED_PANEL_RECT_CENTER_PRIORITY_ENABLED = True
RED_PANEL_CENTER_FALLBACK_ENABLED = True
RED_PANEL_CENTER_MIN_RED_PIXELS = 20
RED_PANEL_CENTER_MIN_RED_PARTS = 3
RED_PANEL_CENTER_DEADBAND_PX = 8.0
RED_PANEL_CENTER_X_DEADBAND_PX = 14.0
RED_PANEL_CENTER_FINE_RADIUS_PX = 52.0
RED_PANEL_CENTER_CONTROL_MAX_DEG = 0.08
RED_PANEL_CENTER_TARGET_WARMUP = 1
RED_PANEL_CENTER_STABLE_SPREAD_PX = 10.0
RED_PANEL_CENTER_MAX_JUMP_PX = 24

# Laser is treated as a fixed camera-relative reference.  Recalibrate these
# if the camera/laser mount changes.
FIXED_LASER_ENABLED = True
FIXED_LASER_CX = 195.0
FIXED_LASER_CY = 93.0
LASER_LOST_RECOVERY_ENABLED = False
LASER_LOST_RECOVERY_DEG = 0.08
LASER_THRESHOLD = (45, 100, 22, 127, -30, 127)
LASER_MIN_PIXELS = 8
LASER_MIN_AREA = 4
LASER_MIN_W = 2
LASER_MIN_H = 2
LASER_MAX_AREA = 90
LASER_MAX_W = 10
LASER_MAX_H = 10
LASER_MIN_DENSITY = 45.0
LASER_MIN_ROUNDNESS = 0.45
LASER_MIN_BRIGHT_PIXELS = 5
LASER_BRIGHT_THRESHOLD = (58, 100, 18, 127, -10, 127)
LASER_HINT_MAX_DIST_PX = 70
LASER_REACQUIRE_MAX_DIST_PX = 220
LASER_PAPER_RELAX_PX = 80

# Filters and control.  Smaller per-frame degree plus higher send rate gives
# smoother motion.  Raise CONTROL_SEND_HZ before raising max degrees.
TARGET_FILTER_WINDOW = 2
TARGET_FILTER_ALPHA = 0.98
TARGET_FILTER_DEADBAND_PX = 0.3
TARGET_WARMUP = 1
LASER_FILTER_WINDOW = 2
LASER_FILTER_ALPHA = 0.85
LASER_FILTER_DEADBAND_PX = 0.4
LASER_WARMUP = 2
ERROR_DEADBAND_PX = 2.0
CONTROL_GAIN = 0.35
CONTROL_MAX_DEG = 0.20
FRAME_CENTER_DEADBAND_PX = 9.0
FRAME_CENTER_FINE_RADIUS_PX = 38.0
FRAME_CENTER_FINE_CONTROL_MAX_DEG = 0.04
RED_RINGS_DEADBAND_PX = 8.0
RED_RINGS_FINE_RADIUS_PX = 36.0
RED_RINGS_FINE_CONTROL_MAX_DEG = 0.08
RED_RINGS_SAFE_CONTROL_MAX_DEG = 0.08
PAPER_CENTER_CONTROL_MAX_DEG = 0.08
FRAME_PART_CONTROL_MAX_DEG = 0.10
MAX_TARGET_JUMP_PX = 70
MAX_LASER_JUMP_PX = 45
TARGET_HOLD_MISSES = 5
LASER_HOLD_MISSES = 8
TARGET_STABLE_SPREAD_PX = 30
LASER_STABLE_SPREAD_PX = 45
TARGET_HOLD_MS = 220
FRAME_CENTER_LOCK_FRAMES = 8
FRAME_CENTER_LOCK_MARGIN_PX = 26

# Soft pitch guard for far/tilted views.  It prevents runaway upward commands
# when the target appears too high in the image.
PITCH_GUARD_ENABLED = True
PITCH_GUARD_MIN_TARGET_CY = 62.0
PITCH_GUARD_SOFT_TARGET_CY = 85.0
PITCH_GUARD_UP_CMD_SIGN = -1.0
PITCH_GUARD_MAX_UP_CMD = 0.04
